"""contact positions

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-02 14:41:55.685815
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contacts", sa.Column("lat", sa.Float(), nullable=True))
    op.add_column("contacts", sa.Column("lon", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contacts", "lon")
    op.drop_column("contacts", "lat")
    # ### end Alembic commands ###
