"""contact favorite block and sound overrides

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-02 16:46:12.596654
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contacts", sa.Column("favorite", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    op.add_column(
        "contacts", sa.Column("blocked", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    op.add_column("conversations", sa.Column("sound", sa.String(length=8), nullable=True))
    op.add_column(
        "messages", sa.Column("suppressed", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "suppressed")
    op.drop_column("conversations", "sound")
    op.drop_column("contacts", "blocked")
    op.drop_column("contacts", "favorite")
    # ### end Alembic commands ###
